name: Build and Analyze

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for accurate analysis

      - uses: SonarSource/sonarqube-scan-action@v4
        with:
          projectKey: khadijahW_resume-files-_91f887f1-fa21-4f0d-a513-6c21d0600de8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://your-sonarqube-server-url
